package com.farmers.test;

import org.json.JSONObject;
import org.json.XML;

public class XMLtoJSON {
	public static int PRETTY_PRINT_INDENT_FACTOR = 4;
    public static String TEST_XML_STRING =
        "<?xml version=\"1.0\" ?><IVRREPORTDATA>\r\n"
        + "    <CALLINFO>\r\n"
        + "		<APPID>S_APP_ID</APPID>\r\n"
        + "		<APP_NAME>S_APPNAME</APP_NAME>\r\n"
        + "		<SESSION_ID>S_SESSIONID</SESSION_ID>\r\n"
        + "		<DNIS>S_DNIS</DNIS>\r\n"
        + "		<VXMLIP>S_SERVERIP</VXMLIP>\r\n"
        + "		<CDN>S_DNIS</CDN>\r\n"
        + "		<CLI>S_CLI</CLI>\r\n"
        + "		<MOBILENUM>S_CLI</MOBILENUM>\r\n"
        + "		<CALLORIGINTYPE>IVR</CALLORIGINTYPE>\r\n"
        + "		<CALLID>S_CALLID</CALLID>\r\n"
        + "		<ICMCALLID>S_ICMGUID</ICMCALLID>\r\n"
        + "		<RTR_CL_KEY>S_RTR_CL_KEY</RTR_CL_KEY>\r\n"
        + "		<RTR_CL_KEY_DAY>S_RTR_CL_KEY_DAY</RTR_CL_KEY_DAY>\r\n"
        + "		<RTR_SEQ_NUM>S_RTR_SEQ_NUM</RTR_SEQ_NUM>\r\n"
        + "		<CALL_START_TIME>S_CALLSTARTDATE</CALL_START_TIME>\r\n"
        + "		<CALL_END_TIME>S_CALLENDDATE</CALL_END_TIME>\r\n"
        + "		<CUSTOMER_SEGMENT>S_CUSTOMER_SEGMENT</CUSTOMER_SEGMENT>\r\n"
        + "		<CUSTOMER_TYPE>S_CUSTOMER_TYPE</CUSTOMER_TYPE>\r\n"
        + "		<CONNECTION_TYPE>S_CONN_TYPE</CONNECTION_TYPE>\r\n"
        + "		<LANGUAGE>S_ACTIVE_LANG</LANGUAGE>\r\n"
        + "		<CALLBARRED>S_BARRED_FLAG</CALLBARRED>\r\n"
        + "		<BARRED_REASON>S_BARRED_REASON</BARRED_REASON>\r\n"
        + "		<CALL_END_TYPE>S_END_TYPE</CALL_END_TYPE>\r\n"
        + "		<CC_CHARGING>Y</CC_CHARGING>\r\n"
        + "		<DISPOSITION_CODE>S_DISPOSITION_CODE</DISPOSITION_CODE>\r\n"
        + "		<ENDTYPE>S_END_TYPE</ENDTYPE>\r\n"
        + "		<ERR_REASON>S_ERR_REASON</ERR_REASON>\r\n"
        + "		<HOW_CALL_ENDED>S_HOW_CALL_ENDED</HOW_CALL_ENDED>\r\n"
        + "		<SKILLNAME>S_PRI_SKILL_NAME</SKILLNAME>\r\n"
        + "		<TRANSFER_CODE>S_TRANSFER_CODE</TRANSFER_CODE>\r\n"
        + "		<TRANSFER_REASON>S_END_TYPE</TRANSFER_REASON>\r\n"
        + "		<LASTFEATURE_ACCESSED>F001</LASTFEATURE_ACCESSED>\r\n"
        + "		<LASTMENU_ACCESSED>S_LAST_MENU_ACCESSED</LASTMENU_ACCESSED>\r\n"
        + "		<MAINMENU_ACCESSED>S_MAIN_MENU_CROSSED</MAINMENU_ACCESSED>\r\n"
        + "		<MENUPATH>S_MENUPATH</MENUPATH>\r\n"
        + "		<IVR_TRAVERSAL_PATH>S_TRAVESAL_HISTORY</IVR_TRAVERSAL_PATH>\r\n"
        + "		<CC_LOW_BALANCE>Y</CC_LOW_BALANCE>\r\n"
        + "		<HOST_FAILURE_TRANSFER>S_HOST_FAILURE_TRANSFER_FLAG</HOST_FAILURE_TRANSFER>\r\n"
        + "		<VAS_SUBCRIPTION>NA</VAS_SUBCRIPTION>\r\n"
        + "		<Direct_Agent_Transfer>NA</Direct_Agent_Transfer>\r\n"
        + "		<RESERVE1>S_APP_TYPE</RESERVE1>\r\n"
        + "		<RESERVE2>S_ENTERPRISE_DATA</RESERVE2>\r\n"
        + "		<RESERVE3/>\r\n"
        + "		<RESERVE4/>\r\n"
        + "		<RESERVE5/>\r\n"
        + "		<RESERVE6/>\r\n"
        + "		<RESERVE7/>\r\n"
        + "		<RESERVE8/>\r\n"
        + "		<RESERVE9/>\r\n"
        + "		<RESERVE10/>\r\n"
        + "	</CALLINFO>\r\n"
        + "	<MENU_DETAIL>\r\n"
        + "		<MENU>\r\n"
        + "			<MENU_COUNTER>1</MENU_COUNTER>\r\n"
        + "			<MENU_STARTTIME>02/10/2009 16:02:49</MENU_STARTTIME>\r\n"
        + "			<MENU_ENDTIME>02/10/2009 16:04:23</MENU_ENDTIME>\r\n"
        + "			<MENU_ID>M001</MENU_ID>\r\n"
        + "			<MENU_OPTION>1/2/3/4/5/6/7/8/9/0/NM/NI/SECURED_DATA/ME</MENU_OPTION>\r\n"
        + "			<MENU_RESERVE1/>\r\n"
        + "			<MENU_RESERVE2/>\r\n"
        + "			<MENU_RESERVE3/>\r\n"
        + "			<MENU_RESERVE4/>\r\n"
        + "			<MENU_TRACKID>1</MENU_TRACKID>\r\n"
        + "		</MENU>\r\n"
        + "	</MENU_DETAIL>\r\n"
        + "	<HOST_DETAIL>\r\n"
        + "		<HOST>\r\n"
        + "			<HOST_ID></HOST_ID>\r\n"
        + "			<HOST_TYPE>DB/Rest</HOST_TYPE>                                                \r\n"
        + "			<HOST_METHOD>H0001-METHODNAME</HOST_METHOD>\r\n"
					/* + "			<HOsST_STARTTIME>20/02/2024 16:02:49</HOST_STARTTIME>\r\n" */
        + "			<HOST_ENDTIME>02/10/2009 16:04:23</HOST_ENDTIME>\r\n"
        + "			<HOST_IN_PARAMS>CARDNO= | CARDTYPE (NAJM/VOYAGER/LOAN)</HOST_IN_PARAMS>\r\n"
        + "			<HOST_OUT_PARAMS>CARDNO= | CARDTYPE (NAJM/VOYAGER/LOAN)</HOST_OUT_PARAMS>\r\n"
        + "			<HOST_FAILURE_REASON> </HOST_FAILURE_REASON>\r\n"
        + "			<HOST_ERROR_CODE>0000 </HOST_ERROR_CODE> \r\n"
        + "			<HOST_RESPONSE>S</HOST_RESPONSE>\r\n"
        + "			<HOST_RESERVE1/>\r\n"
        + "			<HOST_RESERVE2/>\r\n"
        + "			<HOST_RESERVE3/>\r\n"
        + "			<HOST_RESERVE4/>\r\n"
        + "			<HOST_TRACK_ID/>\r\n"
        + "			<HOST_COUNTER>1</HOST_COUNTER>\r\n"
        + "		</HOST>\r\n"
        + "	</HOST_DETAIL>\r\n"
        + "    <FEATUREDETAIL>\r\n"
        + "        <FEATURE>\r\n"
        + "			<FEATURE_COUNTER>1</FEATURE_COUNTER>\r\n"
        + "			<FEATURE_DISPOSITION>CD</FEATURE_DISPOSITION>\r\n"
        + "			<FEATURE_ENDTIME>02/10/2009 16:02:49</FEATURE_ENDTIME>\r\n"
        + "			<FEATURE_ID>BALANCE</FEATURE_ID>\r\n"
        + "			<FEATURE_RESERVE1/>\r\n"
        + "			<FEATURE_RESERVE2/>\r\n"
        + "			<FEATURE_RESERVE3/>\r\n"
        + "			<FEATURE_RESERVE4/>\r\n"
        + "			<FEATURE_STARTTIME>02/10/2009 16:02:49</FEATURE_STARTTIME>\r\n"
        + "			<FEATURE_TRACKID>1</FEATURE_TRACKID>\r\n"
        + "        </FEATURE>\r\n"
        + "    </FEATUREDETAIL>\r\n"
        + "</IVRREPORTDATA>\r\n"
        + "    ";

    public static void main(String[] args) {
        try {
            JSONObject xmlJSONObj = XML.toJSONObject(TEST_XML_STRING);
            String jsonPrettyPrintString = xmlJSONObj.toString(PRETTY_PRINT_INDENT_FACTOR);
            System.out.println(jsonPrettyPrintString);
        } catch (Exception je) {
            System.out.println(je.toString());
        }
    }
}
