Admin.Token.URL = https://EC2AMAZ-ALDVADR/fiivrapi/api/JWTAuthentication/GetAccessToken
Farmers.Token.URL = https://api-ss.farmersinsurance.com/oauthms/v1/oauth/token
Afni.Token.URL = https://dm-us.informaticacloud.com/authz-service/oauth/token

Admin.OAuth.username = ivrapiadmin
Admin.OAuth.password = admin@123

Farmers.Host.ClientID = d0b8876803bb4a3c98f0d3151c2ba5df
Farmers.Host.ClientSecret = 8CC2E651634745D09a24EFA1FB93995b
Farmers.Host.Auth = MG9hd3E5dW9mdVVBMDU2QjgxdDc6bGpYTVJxWURTek01WHhKT0x0Q09iejdDVzlqdTJCZEk3emxhVXB5Ti1nOGlYQWMtWkY0aGhpVjBXYkUxQ3lmOQ==

Afni.Token.Basic.username = aSSFCE2SJc7bwZElQejKYO;
Afni.Token.Basic.Password = A3fYxmKyn;