##AUDIO PATH##
S_AUDIO_PATH=http://$$IP$$/PEWC/

##MULE SOFT CUSTOMER CONSENT DATA POST URL##
S_CUST_CONSENT_URL=https://api-ss.farmersinsurance.com/cstrms/v1/customers/IVR/customerconsent?idType=ipaddress/userid
S_DISCLAIME_RMSG="\"We sometimes reach out to consumers by call and/or text to provide helpful information about products or services. Your consent will permit marketing calls and/or texts to be made on behalf of Farmers, Foremost, Bristol West, Farmers Life and 21st Century insurance entities or their representatives using an automated telephone dialing system and/or an artificial or pre-recorded voice. Your consent is not a condition of purchase.\""