Admin.Token.URL = https://104.156.46.196/IVRAPI_PROD/api/JWTAuthentication/GetAccessToken
Farmers.Token.URL = https://api-ss.farmersinsurance.com/oauthms/v1/oauth/token
Afni.Token.URL = https://dm-us.informaticacloud.com/authz-service/oauth/token


Admin.OAuth.userid = WCh+Dqjk8N0ZnmzhYDAMww==
Admin.OAuth.password = UzsFMzxX2k5oEUrPHr3tEQ==


Farmers.Host.ClientID = 5mhOkcAb9K1AjGjEc+AkBU8Z+1w4FHGjPwoaHawCWSHFR9WbK/Giuw==
Farmers.Host.ClientSecret = giHSENGfgqwyx6VQH+kjPweiqHUErirLmwtqGa8Kn7LFR9WbK/Giuw==
Farmers.Host.Auth = MG9hd3E5dW9mdVVBMDU2QjgxdDc6bGpYTVJxWURTek01WHhKT0x0Q09iejdDVzlqdTJCZEk3emxhVXB5Ti1nOGlYQWMtWkY0aGhpVjBXYkUxQ3lmOQ==
Farmers.Host.frms_region = PROD
Farmers.Host.content_type = application/x-www-form-urlencoded
Farmers.Host.frms_appid = CISCO
Farmers.Host.frms_source = CISCO
Farmers.Host.charset = utf-8
Farmers.Host.URLParameters = grant_type=client_credentials&scope=
Farmers.Host.IVR2TEXT.frms_target = SRM
Farmers.Host.APEX.frms_target = APEX
Farmers.Host.CISCOSRMCTI.frms_target = SRM
Farmers.Host.CLEARHARBOR.frms_target = SRM_CH
Farmers.Host.COMMERCIALSRMCTI.frms_target = SRM
Farmers.Host.FWSSRMCTI.frms_target = SRM
Farmers.Host.KM2.frms_target = SRM_KM2
##Farmers.Host.frms_business = Farmers Insurance.FarmersManagementAL20
Farmers.Host.frms_business = MANAGEMENT




Afni.Token.Basic.userid = 5kz0fexLHcibLz42ULYAoG
Afni.Token.Basic.Password = 7GY8cIqbw
Afni.Token.Content_Type = application/x-www-form-urlencoded
Afni.Token.Charset = utf-8
Afni.Token.URLParameters = grant_type=client_credentials


##Farmers.Token.NonProd.URL = https://api-np-ss.farmersinsurance.com/PLE/oauthms/v1/oauth/token
##Farmers.Host.NonProd.ClientID = o+el930eoFkgimKeD0NTJS93yIQY+ZX+tuXS6K2pD5DFR9WbK/Giuw==
##Farmers.Host.NonProd.ClientSecret = 8LRwiACKfrLjp9FjnAWbG+w1fgUP/GO2yDVWMq0bIVXFR9WbK/Giuw==
##Farmers.Host.NonProd.Auth = 2MG9hd2J2azNia0NubTJ2S0QxdDc6clhFMnhjOWRabzFQRFdJUXluYV9OSDd2VEhRSFlCb1pXWTc3SGlPcGVUTjRLc2pPalB1MmhFUy1UdjdLd1loUQ==

Farmers.Token.NonProd.URL = https://api-np-ss.farmersinsurance.com/PLE/oauthms/v1/oauth/token

Farmers.Host.NonProd.ClientID =DHyKop61WZcMLXXU6FZYpr5PW4SNK4rHqY7HdZkZFjPFR9WbK/Giuw==
Farmers.Host.NonProd.ClientSecret =PSpzwnQq8bR53gWOH+ClTZl82+KbJ0zYfMWPUSBh0kHFR9WbK/Giuw==
Farmers.Host.NonProd.Auth =MG9hd2J2azNia0NubTJ2S0QxdDc6clhFMnhjOWRabzFQRFdJUXluYV9OSDd2VEhRSFlCb1pXWTc3SGlPcGVUTjRLc2pPalB1MmhFUy1UdjdLd1loUQ==
Farmers.Host.NonProd.frms_region=UAT

CISCO.ISMOBILECALLER.KEY=61f441ea-da4b-11ee-aa86-02d05831aba5