CMMF_MN_001_Make_a_Payment=MAKE A PAYMENT
CMMF_MN_001_Account_information=ACCOUNT INFO
CMMF_MN_001_Mailing_address=MAILING ADDRESS
CMMF_MN_001_Farmers_Real_Time_Billing=REAL TIME BILLING
CMMF_MN_001_Website=WEBSITE
CMMF_MN_001_Other_Billing=OTHER BILLING
CBIZ_MN_001_Dial_an_Extension=DIAL AN EXTENSION
CBIZ_MN_001_Property_and_Casualty=PROPERTY AND CASUALTY
CBIZ_MN_001_Workers_Compensation=WORKERS COMP
CBIZ_MN_001_billing_and_Reinstatements=BILLING AND REINSTATEMENT
CBIZ_MN_001_Real_Time_Billing=REAL TIME BILLING
CBIZ_MN_001_Contact_Information=CONTACT INFORMATION
CBIZ_MN_001_Workers_Compensation_Elite=WORKERS COMP ELITE AGENT
CBIZ_MN_001_billing_and_Reinstatements_Elite=BILLING AND REINSTATEMENT ELITE AGENT
CBIZ_MN_001_Property_and_Casualty_Elite=PROPERY AND CASUALTY ELITE AGENT
CBIZ_MN_001_Contact_Information_Play_Out=CONTACT INFORMATION PLAYED OUT
CBIZ_MN_002_Appetite_Eligibility=APPETITE ELIGIBILITY
CBIZ_MN_002_Endorsement=ENDORSEMENT
CBIZ_MN_002_Lienholder=LIENHOLDER
CBIZ_MN_002_Signature_Forms=SIGNATURE FORMS
CBIZ_MN_002_Something_Else=SOMETHING ELSE
CBIZ_MN_003_Real_Time_Billing=REAL TIME BILLING
CBIZ_MN_003_Appetite_Eligibility=APPETITE ELIGIBILITY
CBIZ_MN_003_Audit=AUDIT
CBIZ_MN_003_Something_Else=SOMETHING ELSE
CBIZ_MN_004_YES=NON PRODUCTIVE AUDIT
CBIZ_MN_004_NO=PRODUCTIVE AUDIT
CBIZB_MN_001_Farmers_Real_Time_Billing=FARMERS REAL TIME BILLING
CBIZB_MN_001_Other_Billing=OTHER BILLING
CBIZB_MN_001_Standard_Pay=STANDARD PAY
CBIZB_MN_002_Invoice_and_Electronic_Payments=INVOICE AND ELECTRONIC PAYMENTS
CBIZB_MN_002_Reinstatement=RESINTATEMENT
CBIZB_MN_002_Address_and_Payment_Plan_Changes=ADDRESS AND PAYMENT PLAN CHANGES
CBIZB_MN_002_Something_Else=SOMETHING ELSE
CBIZB_MN_002_Standard_Pay=STANDARD PAY
CIDA_MN_001_Do_Not_Make_Payment=DO NOT MAKE PAYMENT
SIDC_MN_005_Main_Menu=MAINMENU
SIDC_MN_005_Representative=REPRESENTATIVE


## DTMF MENUS ##
CCSC_MN_001_1=REVIEW POLICY
CCSC_MN_001_2=BILLING INQUIRIES
CCSC_MN_001_3=CLAIMS
CCSC_MN_001_NOINPUT=NO SELECTION
CCSC_MN_001_NOMATCH=NOMATCH


## Saikiran Set 3
FMAA_MN_001_Make_a_Payment=MAKE A PAYMENT
FMAA_MN_001_Other_Billing_Questions=OTHER BILLING QUESTIONS
FMAA_MN_001_Existing_Policy=EXISTING POLICY
FMAA_MN_001_Quotes=QUOTES
FMAA_MN_001_Claims=CLAIMS
FMAA_MN_001_Lienholder=LIENHOLDER
FMAA_MN_001_ID_Cards=ID CARDS
FMAA_MN_001_Cancellations=CANCELLATION
FMAA_MN_001_Website_Help=WEBSITE HELP
FMAA_MN_001_Representative=REPRESENTATIVE
FMAA_MN_002_Mobile_Home=MOBILE HOME
FMAA_MN_002_Motorcycle=MOTORCYCLE
FMAA_MN_002_Specialty_Dwelling=SPECIALITY DWELLING
FMAA_MN_002_Landlord=LANDLORD
FMAA_MN_002_Vacant=VACANT
FMAA_MN_002_Seasonal_Home=SEASONAL HOME
FMAA_MN_002_Off_Road_Vehicle=OFF ROAD VEHICLE
FMAA_MN_002_Motor_Home=MOTOR HOME
FMAA_MN_002_Travel_Trailer=TRAVEL TRAILER
FMAA_MN_002_Representative=REPRESENTATIVE
FMAA_MN_003_Mobile_Home=MOBILE HOME
FMAA_MN_003_Motorcycle=MOTORCYCLE
FMAA_MN_003_Specialty_Dwelling=SPECIALITY DWELLING
FMAA_MN_003_Landlord=LANDLORD
FMAA_MN_003_Vacant=VACANT
FMAA_MN_003_Seasonal_Home=SEASONAL HOME
FMAA_MN_003_Off_Road_Vehicle=OFF ROAD VEHICLE
FMAA_MN_003_Motor_Home=MOTOR HOME
FMAA_MN_003_Travel_Trailer=TRAVEL TRAILER
FMAA_MN_003_Representative=REPRESENTATIVE
FMAA_MN_004_Mobile_Home=MOBILE HOME
FMAA_MN_004_Motorcycle=MOTORCYCLE
FMAA_MN_004_Specialty_Dwelling=SPECIALITY DWELLING
FMAA_MN_004_Landlord=LANDLORD
FMAA_MN_004_Vacant=VACANT
FMAA_MN_004_Seasonal_Home=SEASONAL HOME
FMAA_MN_004_Off_Road_Vehicle=OFF ROAD VEHICLE
FMAA_MN_004_Motor_Home=MOTOR HOME
FMAA_MN_004_Travel_Trailer=TRAVEL TRAILER
FMAA_MN_004_Representative=REPRESENTATIVE
FMAM_MN_001_Mobile_Home=MOBILE HOME
FMAM_MN_001_Motorcycle=MOTORCYCLE
FMAM_MN_001_All_Other_Products=ALL OTHER PRODUCTS
FMOM_MN_001_Quotes=QUOTES
FMOM_MN_001_Make_a_Payment=MAKE A PAYMENT
FMOM_MN_001_Billing_Questions=BILLING QUESTIONS
FMOM_MN_001_Policy_Questions=POLICY QUESTIONS
FMOM_MN_001_Claims=CLAIMS
FMOM_MN_001_Lienholder=LIENHOLDER
FMOM_MN_001_Representative=REPRESENTATIVE
FMOM_MN_003_NO=NO
FMOM_MN_003_YES=YES
FMOM_MN_004_Mobile_Home=MOBILE HOME
FMOM_MN_004_Specialty_Dwelling=SPECIALITY DWELLING
FMOM_MN_004_Landlord=LANDLORD
FMOM_MN_004_Vacant_Home=VACANT HOME
FMOM_MN_004_Seasonal_Home=SEASONAL HOME
FMOM_MN_004_Motorcycle=MOTORCYCLE
FMOM_MN_004_Off_Road_Vehicle=OFF ROAD VEHICLE
FMOM_MN_004_Motor_Home=MOTOR HOME
FMOM_MN_004_Travel_Trailer=TRAVEL TRAILER
FMOM_MN_004_Boat=BOAT
FMOM_MN_004_Watercraft=WATERCRAFT
FMOM_MN_004_Representative=REPRESENTATIVE
FMOM_MN_005_Mobile_Home=MOBILE HOME
FMOM_MN_005_Specialty_Dwelling=SPECIALITY DWELLING
FMOM_MN_005_Motorcycle=MOTORCYCLE
FMOM_MN_005_Off_Road_Vehicle=OFF ROAD VEHICLE
FMOM_MN_005_Motor_Home=MOTOR HOME
FMOM_MN_005_Travel_Trailer=TRAVEL TRAILER
FMOM_MN_005_Boat=BOAT
FMOM_MN_005_Watercraft=WATERCRAFT
FMOM_MN_005_Representative=REPRESENTATIVE
FMAMS_MN_001_Mobile_Home=MOBILE HOME
FMAMS_MN_001_Specialty_Dwelling=SPECIALITY DWELLING
BWPM_MN_001_Commissions=COMMISSIONS
BWPM_MN_001_TechnicalSupport=TECHNICAL SUPPORT
BWPM_MN_001_Claims=CLAIMS
BWPM_MN_001_Agency_Contracting_and_Appointments=AGENCY CONTRACTING AND APPOINTMENTS
BWPM_MN_001_Billing=BILLING
BWPM_MN_001_Policy_Questions=POLICY QUESTIONS 
BWPM_MN_001_Extension=EXTENSION
BWBM_MN_001_Customer_Billing=CUSTOMER BILLING
BWBM_MN_001_Policy_Status=POLICY STATUS
BWBM_MN_001_Refunds=REFUNDS
BWBM_MN_001_Commissions=COMMISSIONS
BWBM_MN_001_Other_Billing=OTHER BILLING
BWBP_MN_001_YES=YES
BWBP_MN_001_NO=NO
BWBP_MN_003_YES=YES
BWBP_MN_003_NO=NO
BWBP_MN_005_YES=YES
BWBP_MN_005_NO=NO
BWBP_MN_008_Make_a_Payment=MAKE A PAYMENT
BWBP_MN_008_Outstanding_Balance=OUTSTANDING BALANCE
BWBP_MN_010_YES=YES
BWBP_MN_010_NO=NO
BWBP_MN_002_Lookup_another_Policy=LOOKUP ANOTHER POLICY
BWBP_MN_002_Other_Billing_Questions=OTHER BILLING QUESTIONS
BWBP_MN_002_Main_Menu=MAIN MENU
BWBP_MN_002_Lienholder=LIENHOLDER
BWBP_MN_002_Representative=REPRESENTATIVE
SAAH_MN_001_Billing_Status=BILLING STATUS
SAAH_MN_001_Make_a_Payment=MAKE A PAYMENT
SAAH_MN_001_Claims=CLAIMS
SAAH_MN_001_Payment_Address=PAYMENT ADDRESS
OSPM_MN_001_Make_a_Payment=MAKE A PAYMENT
OSPM_MN_001_Billing=BILLING
OSPM_MN_001_Website_Help=WESITE HELP
OSPM_MN_001_Cancellation=CANCELLATION
OSPM_MN_001_ID_Cards=ID CARDS
OSPM_MN_001_Claims=CLAIMS
OSPM_MN_001_Quotes=QUOTES
OSPM_MN_001_Policy_Assistance=POLICY ASSISTANCE
OSPM_MN_001_Representative=REPRESENTATIVE
OSPM_MN_006_Mobile_Home=MOBILE HOME
OSPM_MN_006_Specialty_Dwelling=SPECIALITY DWELLING
OSPM_MN_006_Motorcycle=MOTORCYCLE
OSPM_MN_006_Off_Road_Vehicle=OFF ROAD VEHICLE
OSPM_MN_006_Motor_Home=MOTOR HOME
OSPM_MN_006_Travel_Trailer=TRAVEL TRAILER
OSPM_MN_006_Boat=BOAT
OSPM_MN_006_Watercraft=WATERCRAFT
OSPM_MN_006_Auto=AUTO
OSPM_MN_006_Representative=REPRESENTATIVE
OSPM_MN_007_Mobile_Home=MOBILE HOME
OSPM_MN_007_Specialty_Dwelling=SPECIALITY DWELLING
OSPM_MN_007_Motorcycle=Motorcycle/Off road vehicle
OSPM_MN_007_Off_Road_Vehicle=Motorcycle/Off road vehicle
OSPM_MN_007_Motor_Home=MOTOR HOME
OSPM_MN_007_Travel_Trailer=TRAVEL TRAILER
OSPM_MN_007_Boat=BOAT
OSPM_MN_007_Watercraft=WATERCRAFT
OSPM_MN_007_Auto=AUTO
OSPM_MN_007_Representative=REPRESENTATIVE
OSPM_MN_008_Mobile_Home=MOBILE HOME
OSPM_MN_008_Specialty_Dwelling=SPECIALITY DWELLING
OSPM_MN_008_Motorcycle=MOTORCYCLE
OSPM_MN_008_Off_Road_Vehicle=OFF ROAD VEHICLE
OSPM_MN_008_Motor_Home=MOTOR HOME
OSPM_MN_008_Travel_Trailer=TRAVEL TRAILER
OSPM_MN_008_Boat=BOAT
OSPM_MN_008_Watercraft=WATERCRAFT
OSPM_MN_008_Auto=AUTO
OSPM_MN_008_Representative=REPRESENTATIVE
OSPM_MN_013_NO=NO
OSPM_MN_013_YES=YES
OSPM_MN_010_YES=YES
OSPM_MN_010_NO=NO
OSPM_MN_016_YES=YES
OSPM_MN_016_NO=NO
SCAH_MN_001_Make_A_Payment=MAKE A PAYMENT
SCAH_MN_001_Billing=BILLING
SCAH_MN_001_Claims=CLAIMS
SPPO_MN_001_Mobile_Home=MOBILE HOME
SPPO_MN_001_Motorcycle=MOTORCYCLE
SPPO_MN_001_Specialty_Dwelling=SPECIALITY DWELLING
SPPO_MN_001_Landlord=LANDLORD
SPPO_MN_001_Vacant_Home=VACANT HOME
SPPO_MN_001_Seasonal_Home=SEASONAL HOME
SPPO_MN_001_Off_Road_Vehicle=OFF ROAD VEHICLE
SPPO_MN_001_Motor_Home=MOTOR HOME
SPPO_MN_001_Travel_Trailer=TRAVEL TRAILER
SPPO_MN_001_Boat=BOAT
SPPO_MN_001_Watercraft=WATERCRAFT
SPPO_MN_001_Representative=REPRESENTATIVE
SPPO_MN_001_Other=DEFAULT

## Jayasurya
ACHA_MN_002_NO=NO
ACHA_MN_002_YES=YES
ACHA_MN_003_Checking=CHECKING
ACHA_MN_003_Saving=SAVING
ACHB_MN_001_NO=NO
ACHB_MN_001_YES=YES
FACM_MN_001_=REPRESENTATIVE
FACM_MN_001_=DEFAULT
FACM_MN_001_Customer=CUSTOMER
FAMM_MN_002_Recreational_Products=RECREATIONAL PRODUCTS
FAMM_MN_002_=REPRESENTATIVE
FAMM_MN_002_=DEFAULT
FAMM_MN_002_=AUTO
FAMM_MN_002_Mobile_Home=MOBILE HOME
FAMM_MN_002_Speciality_Dwelling=SPECIALITY DWELLING
FAMM_MN_002_Representative=REPRESENTATIVE
FAMM_MN_002_Default=DEFAULT
FAMM_MN_001_Policy_Services=POLICY SERVICES
FAMM_MN_001_Billing=BILLING
FAMM_MN_001_Foremost_Star= STAR
FAMM_MN_001_Claims=CLAIMS
FAMM_MN_001_Make_a_Payment=MAKE A PAYMENT
FAMM_MN_001_Antique_Auto=ANTIQUE AUTO
FAMM_MN_001_Supplies=SUPPLIES
FAMM_MN_001_Representative=REPRESENTATIVE
FAMM_MN_001_Default=DEFAULT
FCPO_MN_001_Representative=REPRESENTATIVE
FCPO_MN_001_Default=DEFAULT
FVAN_MN_001_YES=YES
FVAN_MN_001_NO=NO
TFAR_MN_001_Pay_By_Phone=PAY BY PHONE
TFAR_MN_001_Claims=CLAIMS
TFAR_MN_001_Policy_Changes=POLICY CHANGES
TFAR_MN_001_Payment_Address=PAYMENT ADDRESS
TFAR_MN_001_Something_else=SOMETHING ELSE
TFSP_MN_001_Representative=REPRESENTATIVE
TFSP_MN_001_NO=NO
TFFNF_MN_001_Extension=EXTENSION
TFFNF_MN_001_Sales=SALES
TFFNF_MN_001_Services=POLICY SERVICES
TFFNF_MN_001_Claims=CLAIMS
TFFNF_MN_001_Representative=REPRESENTATIVE
TFGPA_MN_003_=PAYMENT AMOUNT 
TFMP_MN_001_Make_The_Payment=MAKE THE PAYMENT 
TFMP_MN_001_Cancel_It_=CANCEL IT
TFPC_MN_005_Card=DIFFERENT CARD
TFPC_MN_005_Bank_Acc=BANK ACCOUNT
TFPM_MN_001_Mailing_Address=MAILING ADDRESS
TFPM_MN_001_Bank_Account=BANK ACCOUNT
TFPM_MN_001_Credit_Card=CREDIT CARD
TFPM_MN_001_Debit_Card=DEBIT CARD
TFPM_MN_001_Representative=REPRESENTATIVE
TFPM_MN_001_Billing_Details=BILLING DETAILS
TFPM_MN_001_Hang_Up=HANG UP
TFSAL_MN_001_Representative=REPRESENTATIVE
TFSAL_MN_001_Default=DEFAULT












## Sabari
## FARMER SALES SET 2
FSLS_MN_001_Auto=AUTO
FSLS_MN_001_Homeowners=HOME OWNERS
FSLS_MN_001_Home_Owners=HOME OWNERS
FSLS_MN_001_Something Else=SOMETHINGELSE
FSLS_MN_001_No Selection=NOSELECTION
FSLS_MN_001_Motorcycle=MOTORCYCLE
FSLS_MN_001_Watercraft=WATERCRAFT
FSLS_MN_001_Representative=REPRESENTATIVE
FSLS_MN_001_RV=RV

## SET - 4
FNAG_MN_001_Dial_an_Extension=DIAL AN EXTENSION
FNAG_MN_001_New_Business=NEW BUSINESS
FNAG_MN_001_Underwriting=UNDERWRITING
FNAG_MN_001_Policy_Services=POLICY SERVICES
FNAG_MN_001_Default=DEFAULT
FNAG_MN_001_Pre_Sales_Support=PRE SALES SUPPORT
FNAG_MN_001_Commissions=COMMISSIONS
FNAG_MN_001_Annuities=ANNUITIES
FNAG_MN_001_Commissions=CLAIMS

##Farmers Hawaaii - Mathavan
FMHB_MN_001_Dial_an_Extension=DIAL AN EXTENSION
FMHB_MN_001_Personal=PERSONAL
FMHB_MN_001_Commercial=COMMERCIAL
FMHB_MN_001_New_Auto_Quote=NEW AUTO QUOTE
FMHB_MN_001_Representative=REPRESENTATIVE

##FNWL CUSTOMER -- Mathavan T
FNCS_MN_001_Dial_an_Extension=DIAL AN EXTENSION
FNCS_MN_001_Customer_Service=CUSTOMER SERVICE
FNCS_MN_001_Claims=CLAIMS
FNCS_MN_001_Annuities=ANNUITIES
FNCS_MN_001_New_Applications=NEW APPLICATIONS

## SHARED MAINMENU

SMM_MN_001_ID_Cards=IDCARDS
SMM_MN_001_Sales_or_Quotes=SALES/QUOTES
SMM_MN_001_Billing_and_Payments=BILLINGS&PAYMENTS
SMM_MN_001_Agent_Information=AGENTINFO/CONTACT AN AGENT
SMM_MN_001_Policy_Questions=POLICYCHANGES&QUESTIONS
SMM_MN_001_Policy_Changes=POLICYCHANGES&QUESTIONS
SMM_MN_001_Representative=REPRESENTATIVE
SMM_MN_001_Cancel_Policy=CANCELPOLICY
SMM_MN_001_Website_Help=WEBSITEHELP/PASSWORDRESET

SAAH_MN_002_Make_a_Payment=MAKE A PAYMENT
SAAH_MN_002_Lookup_Another_Policy=LOOK UP FOR ANOTHER POLICY
SAAH_MN_002_Payment_address=PAYMENT ADDRESS
SAAH_MN_002_Repeat=REPEAT

SSAAH_MN_001_BW_Billing=BW BILLING
SSAAH_MN_001_BW_Claims=BW CLAIMS
SSAAH_MN_001_Specialty_Billing=SPECIALITY BILLING
SSAAH_MN_001_Specialty_Claims=SPECIALITY CLAIMS

ACHB_MN_001_NO=NO
TFGPA_MN_001_Custom_Amount=CUSTOM AMOUNT
TFGPA_MN_001_Full_Policy_Balance=FULL POLICY BALANCE
TFGPA_MN_002_Custom_Amount=CUSTOM AMOUNT
TFGPA_MN_002_full_balance=FULL BALANCE
TFGPA_MN_003_Payment_Amount=PAYMENT AMOUNT
FACM_MN_001_Lienholder=LINEHOLDER
FACM_MN_001_Agent=AGENT

##MSP Fixes
OSPM_MN_014_Customer=Customer/Default
OSPM_MN_014_Agent=
OSPM_MN_014_Lienholder=

###FASPC_MN_001
FASPC_MN_001_Got_Policy=POLICY NUMBER

